-- Statcast pitch-by-pitch 生データテーブル定義 (119カラム)
CREATE DATABASE IF NOT EXISTS statcast;

CREATE TABLE IF NOT EXISTS statcast.statcast_raw (
    `pitch_type` Nullable(String),
    `game_date` Date,
    `release_speed` Nullable(Float64),
    `release_pos_x` Nullable(Float64),
    `release_pos_z` Nullable(Float64),
    `batter` Int64 DEFAULT 0,
    `pitcher` Int64 DEFAULT 0,
    `events` Nullable(String),
    `description` Nullable(String),
    `spin_dir` Nullable(String),
    `spin_rate_deprecated` Nullable(String),
    `break_angle_deprecated` Nullable(String),
    `break_length_deprecated` Nullable(String),
    `zone` Nullable(Int64),
    `des` Nullable(String),
    `game_type` Nullable(String),
    `stand` Nullable(String),
    `p_throws` Nullable(String),
    `home_team` Nullable(String),
    `away_team` Nullable(String),
    `type` Nullable(String),
    `hit_location` Nullable(Int64),
    `bb_type` Nullable(String),
    `balls` Nullable(Int64),
    `strikes` Nullable(Int64),
    `game_year` Nullable(Int64),
    `pfx_x` Nullable(Float64),
    `pfx_z` Nullable(Float64),
    `plate_x` Nullable(Float64),
    `plate_z` Nullable(Float64),
    `on_3b` Nullable(Int64),
    `on_2b` Nullable(Int64),
    `on_1b` Nullable(Int64),
    `outs_when_up` Nullable(Int64),
    `inning` Nullable(Int64),
    `inning_topbot` Nullable(String),
    `hc_x` Nullable(Float64),
    `hc_y` Nullable(Float64),
    `tfs_deprecated` Nullable(String),
    `tfs_zulu_deprecated` Nullable(String),
    `umpire` Nullable(String),
    `sv_id` Nullable(String),
    `vx0` Nullable(Float64),
    `vy0` Nullable(Float64),
    `vz0` Nullable(Float64),
    `ax` Nullable(Float64),
    `ay` Nullable(Float64),
    `az` Nullable(Float64),
    `sz_top` Nullable(Float64),
    `sz_bot` Nullable(Float64),
    `hit_distance_sc` Nullable(Float64),
    `launch_speed` Nullable(Float64),
    `launch_angle` Nullable(Float64),
    `effective_speed` Nullable(Float64),
    `release_spin_rate` Nullable(Float64),
    `release_extension` Nullable(Float64),
    `game_pk` Int64 DEFAULT 0,
    `fielder_2` Nullable(Int64),
    `fielder_3` Nullable(Int64),
    `fielder_4` Nullable(Int64),
    `fielder_5` Nullable(Int64),
    `fielder_6` Nullable(Int64),
    `fielder_7` Nullable(Int64),
    `fielder_8` Nullable(Int64),
    `fielder_9` Nullable(Int64),
    `release_pos_y` Nullable(Float64),
    `estimated_ba_using_speedangle` Nullable(Float64),
    `estimated_woba_using_speedangle` Nullable(Float64),
    `woba_value` Nullable(Float64),
    `woba_denom` Nullable(Int64),
    `babip_value` Nullable(Int64),
    `iso_value` Nullable(Int64),
    `launch_speed_angle` Nullable(Int64),
    `at_bat_number` Int64 DEFAULT 0,
    `pitch_number` Int64 DEFAULT 0,
    `pitch_name` Nullable(String),
    `home_score` Nullable(Int64),
    `away_score` Nullable(Int64),
    `bat_score` Nullable(Int64),
    `fld_score` Nullable(Int64),
    `post_away_score` Nullable(Int64),
    `post_home_score` Nullable(Int64),
    `post_bat_score` Nullable(Int64),
    `post_fld_score` Nullable(Int64),
    `if_fielding_alignment` Nullable(String),
    `of_fielding_alignment` Nullable(String),
    `spin_axis` Nullable(Int64),
    `delta_home_win_exp` Nullable(Float64),
    `delta_run_exp` Nullable(Float64),
    `bat_speed` Nullable(Float64),
    `swing_length` Nullable(Float64),
    `miss_distance` Nullable(Float64),
    `estimated_slg_using_speedangle` Nullable(Float64),
    `delta_pitcher_run_exp` Nullable(Float64),
    `hyper_speed` Nullable(Float64),
    `home_score_diff` Nullable(Int64),
    `bat_score_diff` Nullable(Int64),
    `home_win_exp` Nullable(Float64),
    `bat_win_exp` Nullable(Float64),
    `age_pit_legacy` Nullable(Int64),
    `age_bat_legacy` Nullable(Int64),
    `age_pit` Nullable(Int64),
    `age_bat` Nullable(Int64),
    `n_thruorder_pitcher` Nullable(Int64),
    `n_priorpa_thisgame_player_at_bat` Nullable(Int64),
    `pitcher_days_since_prev_game` Nullable(Int64),
    `batter_days_since_prev_game` Nullable(Int64),
    `pitcher_days_until_next_game` Nullable(Int64),
    `batter_days_until_next_game` Nullable(Int64),
    `api_break_z_with_gravity` Nullable(Float64),
    `api_break_x_arm` Nullable(Float64),
    `api_break_x_batter_in` Nullable(Float64),
    `arm_angle` Nullable(Float64),
    `attack_angle` Nullable(Float64),
    `attack_direction` Nullable(Float64),
    `swing_path_tilt` Nullable(Float64),
    `intercept_ball_minus_batter_pos_x_inches` Nullable(Float64),
    `intercept_ball_minus_batter_pos_y_inches` Nullable(Float64)
)
ENGINE = ReplacingMergeTree()
PARTITION BY toYYYYMM(game_date)
ORDER BY (game_date, pitcher, batter, game_pk, at_bat_number, pitch_number)
SETTINGS allow_nullable_key = 1;

-- チームマスタテーブル定義 (全データ保持)
CREATE TABLE IF NOT EXISTS statcast.teams (
    `team_id` UInt32,
    `name` String,
    `abbreviation` LowCardinality(String),
    `team_name` String,
    `location_name` String,
    `league_id` Nullable(UInt32),
    `league_name` Nullable(String),
    `division_id` Nullable(UInt32),
    `division_name` Nullable(String),
    `venue_id` Nullable(UInt32),
    `venue_name` Nullable(String),
    `active` UInt8 DEFAULT 1,
    `created_at` DateTime DEFAULT now(),
    `updated_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (team_id);

-- 選手マスタテーブル定義 (全データ保持)
CREATE TABLE IF NOT EXISTS statcast.players (
    `player_id` UInt64,
    `full_name` String,
    `first_name` String,
    `last_name` String,
    `last_first_name` String,
    `primary_number` Nullable(String),
    `current_team_id` Nullable(UInt32),
    `primary_position_code` Nullable(String),
    `primary_position_name` Nullable(String),
    `primary_position_type` Nullable(String),
    `primary_position_abbreviation` LowCardinality(Nullable(String)),
    `bat_side` LowCardinality(Nullable(String)),
    `pitch_hand` LowCardinality(Nullable(String)),
    `active` UInt8 DEFAULT 1,
    `created_at` DateTime DEFAULT now(),
    `updated_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (player_id);

-- 試合日程・結果テーブル定義 (全データ保持)
CREATE TABLE IF NOT EXISTS statcast.games (
    `game_pk` UInt64,
    `game_date` Date,
    `game_date_time` Nullable(DateTime),
    `season` UInt16,
    `game_type` LowCardinality(String),
    `status` LowCardinality(String),
    `status_code` LowCardinality(Nullable(String)),
    `home_team_id` UInt32,
    `home_team_name` String,
    `away_team_id` UInt32,
    `away_team_name` String,
    `home_score` Nullable(UInt16),
    `away_score` Nullable(UInt16),
    `is_winner_home` Nullable(UInt8),
    `is_winner_away` Nullable(UInt8),
    `venue_id` Nullable(UInt32),
    `venue_name` Nullable(String),
    `created_at` DateTime DEFAULT now(),
    `updated_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (season, game_date, game_pk);

-- ボックススコア: チーム成績テーブル定義
CREATE TABLE IF NOT EXISTS statcast.boxscore_teams (
    `game_pk` UInt64,
    `team_id` UInt32,
    `team_name` String,
    `is_home` UInt8,
    -- チーム打撃 (batting)
    `fly_outs` UInt16,
    `ground_outs` UInt16,
    `air_outs` UInt16,
    `runs` UInt16,
    `doubles` UInt16,
    `triples` UInt16,
    `home_runs` UInt16,
    `strike_outs` UInt16,
    `base_on_balls` UInt16,
    `intentional_walks` UInt16,
    `hits` UInt16,
    `hit_by_pitch` UInt16,
    `at_bats` UInt16,
    `obp` Nullable(Float32),
    `slg` Nullable(Float32),
    `ops` Nullable(Float32),
    `avg` Nullable(Float32),
    `caught_stealing` UInt16,
    `stolen_bases` UInt16,
    `ground_into_double_play` UInt16,
    `plate_appearances` UInt16,
    `total_bases` UInt16,
    `rbi` UInt16,
    `left_on_base` UInt16,
    `sac_bunts` UInt16,
    `sac_flies` UInt16,
    -- チーム投球 (pitching)
    `pitching_runs` UInt16,
    `pitching_doubles` UInt16,
    `pitching_triples` UInt16,
    `pitching_home_runs` UInt16,
    `pitching_strike_outs` UInt16,
    `pitching_base_on_balls` UInt16,
    `pitching_intentional_walks` UInt16,
    `pitching_hits` UInt16,
    `pitching_at_bats` UInt16,
    `number_of_pitches` UInt16,
    `era` Nullable(Float32),
    `innings_pitched` String,
    `earned_runs` UInt16,
    `whip` Nullable(Float32),
    `batters_faced` UInt16,
    `outs` UInt16,
    `pitches_thrown` UInt16,
    `balls` UInt16,
    `strikes` UInt16,
    `strike_percentage` Nullable(Float32),
    `hit_batsmen` UInt16,
    `balks` UInt16,
    `wild_pitches` UInt16,
    `pickoffs` UInt16,
    -- チーム守備 (fielding)
    `fielding_assists` UInt16,
    `fielding_put_outs` UInt16,
    `fielding_errors` UInt16,
    `fielding_chances` UInt16,
    `fielding_passed_ball` UInt16,
    `fielding_pickoffs` UInt16,
    `created_at` DateTime DEFAULT now(),
    `updated_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (game_pk, team_id);

-- ボックススコア: 個人打撃成績テーブル定義
CREATE TABLE IF NOT EXISTS statcast.boxscore_batting (
    `game_pk` UInt64,
    `team_id` UInt32,
    `player_id` UInt64,
    `jersey_number` Nullable(String),
    `position_code` Nullable(String),
    `position_name` Nullable(String),
    `position_type` Nullable(String),
    `position_abbreviation` Nullable(String),
    `all_positions` Array(String),
    `batting_order` Nullable(String),
    `is_starter` UInt8,
    `is_substitute` UInt8,
    -- 打撃成績
    `summary` Nullable(String),
    `games_played` UInt8,
    `fly_outs` UInt16,
    `ground_outs` UInt16,
    `air_outs` UInt16,
    `runs` UInt16,
    `doubles` UInt16,
    `triples` UInt16,
    `home_runs` UInt16,
    `strike_outs` UInt16,
    `base_on_balls` UInt16,
    `intentional_walks` UInt16,
    `hits` UInt16,
    `hit_by_pitch` UInt16,
    `at_bats` UInt16,
    `caught_stealing` UInt16,
    `stolen_bases` UInt16,
    `ground_into_double_play` UInt16,
    `ground_into_triple_play` UInt16,
    `plate_appearances` UInt16,
    `total_bases` UInt16,
    `rbi` UInt16,
    `left_on_base` UInt16,
    `sac_bunts` UInt16,
    `sac_flies` UInt16,
    `catchers_interference` UInt16,
    `pickoffs` UInt16,
    `pop_outs` UInt16,
    `line_outs` UInt16,
    `created_at` DateTime DEFAULT now(),
    `updated_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (game_pk, team_id, player_id);

-- ボックススコア: 個人投球成績テーブル定義
CREATE TABLE IF NOT EXISTS statcast.boxscore_pitching (
    `game_pk` UInt64,
    `team_id` UInt32,
    `player_id` UInt64,
    `jersey_number` Nullable(String),
    `position_code` Nullable(String),
    `position_name` Nullable(String),
    `position_type` Nullable(String),
    `position_abbreviation` Nullable(String),
    `all_positions` Array(String),
    `pitching_order` UInt8,
    `is_starter` UInt8,
    -- 投球成績
    `summary` Nullable(String),
    `note` Nullable(String),
    `games_played` UInt8,
    `games_started` UInt8,
    `fly_outs` UInt16,
    `ground_outs` UInt16,
    `air_outs` UInt16,
    `runs` UInt16,
    `doubles` UInt16,
    `triples` UInt16,
    `home_runs` UInt16,
    `strike_outs` UInt16,
    `base_on_balls` UInt16,
    `intentional_walks` UInt16,
    `hits` UInt16,
    `hit_by_pitch` UInt16,
    `at_bats` UInt16,
    `number_of_pitches` UInt16,
    `innings_pitched` String,
    `wins` UInt8,
    `losses` UInt8,
    `saves` UInt8,
    `save_opportunities` UInt8,
    `holds` UInt8,
    `blown_saves` UInt8,
    `earned_runs` UInt16,
    `batters_faced` UInt16,
    `outs` UInt16,
    `complete_games` UInt8,
    `shutouts` UInt8,
    `pitches_thrown` UInt16,
    `balls` UInt16,
    `strikes` UInt16,
    `strike_percentage` Nullable(Float32),
    `hit_batsmen` UInt16,
    `balks` UInt16,
    `wild_pitches` UInt16,
    `pickoffs` UInt16,
    `rbi` UInt16,
    `games_finished` UInt8,
    `inherited_runners` UInt16,
    `inherited_runners_scored` UInt16,
    `catchers_interference` UInt16,
    `sac_bunts` UInt16,
    `sac_flies` UInt16,
    `passed_ball` UInt16,
    `pop_outs` UInt16,
    `line_outs` UInt16,
    `created_at` DateTime DEFAULT now(),
    `updated_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (game_pk, team_id, player_id);

-- ボックススコア: 選手の試合別守備位置詳細テーブル定義
CREATE TABLE IF NOT EXISTS statcast.boxscore_positions (
    `game_pk` UInt64,
    `team_id` UInt32,
    `player_id` UInt64,
    `position_order` UInt8,
    `position_code` String,
    `position_name` String,
    `position_type` String,
    `position_abbreviation` String,
    `created_at` DateTime DEFAULT now(),
    `updated_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (game_pk, team_id, player_id, position_order);

