-- Statcast pitch-by-pitch 生データテーブル定義 (119カラム)
CREATE DATABASE IF NOT EXISTS statcast;

CREATE TABLE IF NOT EXISTS statcast.statcast_raw (
    `pitch_type` Nullable(String),
    `game_date` Date,
    `release_speed` Nullable(Float64),
    `release_pos_x` Nullable(Float64),
    `release_pos_z` Nullable(Float64),
    `player_name` Nullable(String),
    `batter` Int64 DEFAULT 0,
    `pitcher` Int64 DEFAULT 0,
    `events` Nullable(String),
    `description` Nullable(String),
    `spin_dir` Nullable(String),
    `spin_rate_deprecated` Nullable(String),
    `break_angle_deprecated` Nullable(String),
    `break_length_deprecated` Nullable(String),
    `zone` Nullable(Int64),
    `des` Nullable(String),
    `game_type` Nullable(String),
    `stand` Nullable(String),
    `p_throws` Nullable(String),
    `home_team` Nullable(String),
    `away_team` Nullable(String),
    `type` Nullable(String),
    `hit_location` Nullable(Int64),
    `bb_type` Nullable(String),
    `balls` Nullable(Int64),
    `strikes` Nullable(Int64),
    `game_year` Nullable(Int64),
    `pfx_x` Nullable(Float64),
    `pfx_z` Nullable(Float64),
    `plate_x` Nullable(Float64),
    `plate_z` Nullable(Float64),
    `on_3b` Nullable(Int64),
    `on_2b` Nullable(Int64),
    `on_1b` Nullable(Int64),
    `outs_when_up` Nullable(Int64),
    `inning` Nullable(Int64),
    `inning_topbot` Nullable(String),
    `hc_x` Nullable(Float64),
    `hc_y` Nullable(Float64),
    `tfs_deprecated` Nullable(String),
    `tfs_zulu_deprecated` Nullable(String),
    `umpire` Nullable(String),
    `sv_id` Nullable(String),
    `vx0` Nullable(Float64),
    `vy0` Nullable(Float64),
    `vz0` Nullable(Float64),
    `ax` Nullable(Float64),
    `ay` Nullable(Float64),
    `az` Nullable(Float64),
    `sz_top` Nullable(Float64),
    `sz_bot` Nullable(Float64),
    `hit_distance_sc` Nullable(Float64),
    `launch_speed` Nullable(Float64),
    `launch_angle` Nullable(Float64),
    `effective_speed` Nullable(Float64),
    `release_spin_rate` Nullable(Float64),
    `release_extension` Nullable(Float64),
    `game_pk` Int64 DEFAULT 0,
    `fielder_2` Nullable(Int64),
    `fielder_3` Nullable(Int64),
    `fielder_4` Nullable(Int64),
    `fielder_5` Nullable(Int64),
    `fielder_6` Nullable(Int64),
    `fielder_7` Nullable(Int64),
    `fielder_8` Nullable(Int64),
    `fielder_9` Nullable(Int64),
    `release_pos_y` Nullable(Float64),
    `estimated_ba_using_speedangle` Nullable(Float64),
    `estimated_woba_using_speedangle` Nullable(Float64),
    `woba_value` Nullable(Float64),
    `woba_denom` Nullable(Int64),
    `babip_value` Nullable(Int64),
    `iso_value` Nullable(Int64),
    `launch_speed_angle` Nullable(Int64),
    `at_bat_number` Int64 DEFAULT 0,
    `pitch_number` Int64 DEFAULT 0,
    `pitch_name` Nullable(String),
    `home_score` Nullable(Int64),
    `away_score` Nullable(Int64),
    `bat_score` Nullable(Int64),
    `fld_score` Nullable(Int64),
    `post_away_score` Nullable(Int64),
    `post_home_score` Nullable(Int64),
    `post_bat_score` Nullable(Int64),
    `post_fld_score` Nullable(Int64),
    `if_fielding_alignment` Nullable(String),
    `of_fielding_alignment` Nullable(String),
    `spin_axis` Nullable(Int64),
    `delta_home_win_exp` Nullable(Float64),
    `delta_run_exp` Nullable(Float64),
    `bat_speed` Nullable(Float64),
    `swing_length` Nullable(Float64),
    `miss_distance` Nullable(Float64),
    `estimated_slg_using_speedangle` Nullable(Float64),
    `delta_pitcher_run_exp` Nullable(Float64),
    `hyper_speed` Nullable(Float64),
    `home_score_diff` Nullable(Int64),
    `bat_score_diff` Nullable(Int64),
    `home_win_exp` Nullable(Float64),
    `bat_win_exp` Nullable(Float64),
    `age_pit_legacy` Nullable(Int64),
    `age_bat_legacy` Nullable(Int64),
    `age_pit` Nullable(Int64),
    `age_bat` Nullable(Int64),
    `n_thruorder_pitcher` Nullable(Int64),
    `n_priorpa_thisgame_player_at_bat` Nullable(Int64),
    `pitcher_days_since_prev_game` Nullable(Int64),
    `batter_days_since_prev_game` Nullable(Int64),
    `pitcher_days_until_next_game` Nullable(Int64),
    `batter_days_until_next_game` Nullable(Int64),
    `api_break_z_with_gravity` Nullable(Float64),
    `api_break_x_arm` Nullable(Float64),
    `api_break_x_batter_in` Nullable(Float64),
    `arm_angle` Nullable(Float64),
    `attack_angle` Nullable(Float64),
    `attack_direction` Nullable(Float64),
    `swing_path_tilt` Nullable(Float64),
    `intercept_ball_minus_batter_pos_x_inches` Nullable(Float64),
    `intercept_ball_minus_batter_pos_y_inches` Nullable(Float64)
)
ENGINE = ReplacingMergeTree()
PARTITION BY toYYYYMM(game_date)
ORDER BY (game_date, pitcher, batter, game_pk, at_bat_number, pitch_number)
SETTINGS allow_nullable_key = 1;
